image: python:3.9

pipelines:
  default:
    - step:
        name: "Instalar dependências"
        caches:
          - pip
        script:
          - pip install -r requirements.txt

    - step:
        name: "Verificação de Qualidade de Código"
        script:
          - pip install flake8
          - flake8 .

    - step:
        name: "Rodar Testes"
        script:
          - python -m unittest discover

    - step:
        name: "Configurar Permissão para Deploy"
        script:
          - chmod +x deploy.sh

    - step:
        name: "Deploy"
        script:
          - ./deploy.sh

    # Step manual de notificação
    - step:
        name: "Notificar Sucesso no Slack"
        trigger: manual  # Tornando este step manual
        script:
          - curl -X POST --data-urlencode 'payload={"text":"Pipeline de Deploy finalizado com sucesso"}' https://hooks.slack.com/services/SEU/WEBHOOK

  branches:
    main:
      - step:
          name: "Deploy para Main"
          script:
            - chmod +x deploy.sh
            - ./deploy.sh

  tags:
    "v*":
      - step:
          name: "Deploy para Produção"
          script:
            - chmod +x deploy.sh
            - ./deploy.sh