image: python:3.9

pipelines:
  default:
    - step:
        name: "Instalar dependências"
        caches:
          - pip
        script:
          - pip install -r requirements.txt

    - step:
        name: "Verificação de Qualidade de Código"
        script:
          - pip install flake8
          - flake8 .

    - step:
        name: "Rodar Testes"
        script:
          - python -m unittest discover

    # Step manual para revisão de qualidade
    - step:
        name: "Revisão Manual de Código"
        trigger: manual
        script:
          - echo "Revisão manual de código iniciada"
          - echo "Certifique-se de verificar os padrões de formatação e segurança."

    # Step manual para deploy em ambiente de staging
    - step:
        name: "Deploy para Staging"
        trigger: manual
        script:
          - chmod +x deploy.sh
          - ./deploy.sh staging

    # Step manual para deploy em produção
    - step:
        name: "Deploy para Produção"
        trigger: manual
        script:
          - chmod +x deploy.sh
          - ./deploy.sh production

    # Step manual para notificação de sucesso no Slack
    - step:
        name: "Notificar Sucesso no Slack"
        trigger: manual
        script:
          - curl -X POST --data-urlencode 'payload={"text":"Pipeline finalizado com sucesso"}' https://hooks.slack.com/services/SEU/WEBHOOK

  branches:
    main:
      - step:
          name: "Deploy Automático na Main"
          script:
            - chmod +x deploy.sh
            - ./deploy.sh