# Definir a imagem Docker que será utilizada
image: python:3.9

# Configuração do pipeline
pipelines:
  default:
    # Passo 1: Instalar as dependências
    - step:
        name: "Instalar dependências"
        caches:
          - pip  # Cache das dependências para otimizar as execuções
        script:
          - pip install -r requirements.txt  # Instalar pacotes listados no requirements.txt

    # Passo 2: Rodar os testes
    - step:
        name: "Rodar Testes"
        script:
          - python -m unittest discover  # Comando para rodar testes unitários

  branches:
    # Deploy quando estiver na branch main (pode adicionar mais branches conforme necessário)
    main:
      - step:
          name: "Deploy"
          script:
            - chmod +x deploy.sh  # Garantir permissões de execução do script deploy.sh
            - ./deploy.sh         # Executar o script de deploy